name: Test event and triggers
on:
    workflow_dispatch: 
    push:
      branches-ignore: 
        - main
    pull_request: 
       
            


        
jobs:
    events_trigger:
        if: ${{ contains(github.ref,'main')}}
        
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: check hello world
              run: docker pull hello-world
            
            - name: run hello world
              run: docker run hello-world

            - name: create a file
              if: ${{ job.status }}
              run: |
                 cat >> status.txt <<EOF
                    ${{ github.repository }} -- ${{ github.event }} ---> ${{ job.status }}
                    EOF

            - name: add comment
              uses: mshick/add-pr-comment@v2
              env:
                content: $(cat status.txt)
              if: (contains(fromJSON('["pull_request", "push"]'), github.event_name))
              with:
                        message: |
                            **Howdie!** The job has the status ${{ env.content }}

    
    