name: Multi job
on: 
    - push
    - pull_request
permissions: 
    contents:  write

env:
    project-id: 1342
    project-version: 1.0
    current_date: $(date +'%Y-%m-%d')

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: Add the new file
              run: | 
                mkdir -p multi
                cat > multi/text-${{ env.current_date }}.txt << EOF
                Welcome to github action workflows for ${{ env.project-id}} and his age: ${{ env.project-version }}
                $(date +'%Y-%m-%d')
                EOF
            - name: upload new files
              uses: actions/upload-artifact@v4
              with:
                  name: sample-artifact
                  path: multi/text-${{ env.current_date }}.txt 

    test-job:
        needs: build-job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup artifact path
              run: |
                mkdir -p ${{ github.workspace }}/artifact
                echo "artifact_path=${{ github.workspace }}/artifact" >> $GITHUB_ENV
               
            - uses: actions/download-artifact@v4
              with:
                name: sample-artifact
                path: ${{ env.artifact_path }}

            - name: Display structure of downloaded files
              run: ls -R ${{ env.artifact_path }}
            

    deploy-job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            - name: deploy jobs
              run: echo "Test jobs"