name: sample flow
on: 
    - push
    - pull_request

permissions:
    contents: write
jobs:
    first_job:
        runs-on: ubuntu-latest
        env:
            name: John
            age: 12
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get current date
              id: date
              run: |
                echo "current_date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
                echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT
                echo ${{ steps.date.outputs.SELECTED_COLOR }}
                  
            - name: Display the name
              run: echo `Hello world for ${{ env.name}}`

            - name: Add the new file
              run: | 
                cat > text.txt << EOF
                Welcome to github action workflows for ${{ env.name}} and his age: ${{ env.age}}
                ${{ steps.date_checker.output.current_date}}
                EOF
           
            - name: Display the output
              run: |
                cat text.txt 
                ls -al
                
            - name: add file and commit back to git hub
              uses: EndBug/add-and-commit@v9
              with:
                message: Show GitHub logo
                committer_name: GitHub Actions
                committer_email: 41898282+github-actions[bot]@users.noreply.github.com