name: sample flow
on: 
    - push
    - pull_request

jobs:
    first_job:
        runs-on: ubuntu-latest
        env:
            name: John
            age: 12
        steps:
            - name: Display the name
              run: echo `Hello world for ${{ env.name}}`

            - name: Add the new file
              run: | 
                cat > text.txt << EOF
                Welcome to github action workflows for ${{ env.name}} and his age: ${{ env.age}}
                EOF
            - name: Add the new file
              run: | 
                cat >> text.txt /
                Welcome to github action workflows for ${{ env.name}} and his age: ${{ env.age}} /
                ^D

            - name: Display the output
              run: |
                cat text.txt 
                ls -al