name: sample flow
on: 
    - push
    - pull_request

permissions:
    contents: write
jobs:
    first_job:
        runs-on: ubuntu-latest
        env:
            name: John
            age: 12
        steps:
            - name: Checkout
              uses: actions/checkout@v4

           
            - name: Get current date
              id: date
              run: |
                echo "current_date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
            
           
            - name: Add the new file
              run: | 
                cat > text-$(date +'%Y-%m-%d').txt << EOF
                Welcome to github action workflows for ${{ env.name}} and his age: ${{ env.age}}
                $(date +'%Y-%m-%d')
                EOF
           
            - name: Display the output
              run: |
                cat text-${{ steps.date.outputs.current_date}}.txt 
                ls -al
                echo $(history) >> text-${{ steps.date.outputs.current_date}}.txt

            - name: add file and commit back to git hub
              uses: EndBug/add-and-commit@v9
              with:
                message: Show GitHub logo
                committer_name: GitHub Actions
                committer_email: 41898282+github-actions[bot]@users.noreply.github.com