name: Display secrets and env file
on: 
    - push
    - pull_request

jobs:
    secrtes_variable:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: add a new file
          run: |
             echo ${{ vars.USERNAME }} > file.txt
             echo ${{ secrets.PASSWORD }} >> file.txt
             cat file.txt
